### ISSUE TITLE
求个步骤文档

### ISSUE THREAD

**Issue by sa-da-sa-da** [jimlee2002/WoZaiXiaoYuanPuncher-Actions#1]
麻烦写个教程，不然不知道每个密钥是什么东西

**Comment by jimlee2002** [comment]
请稍等，readme正在腹泻式更新……

**Comment by jimlee2002** [comment]
2020.8.7 2:20，文字版已写好，图片将在稍后传上来

**Comment by jimlee2002** [comment]
2021.8.7 4:00，简要图片已上传，并修正初版readme，已基本完成步骤文档。
本 issuse 将关闭，感谢支持！如有任何问题，欢迎再发 issuse 😎

**Comment by jimlee2002** [comment]
另：脚本有细微更新，记得 fetch 一下！😉
