### ISSUE TITLE
{'code': 101, 'message': '用户名或密码错误,还可再试2次'}

### ISSUE THREAD

**Issue by wxm78** [jimlee2002/WoZaiXiaoYuanPuncher-Actions#14]
![屏幕截图 2021-11-03 114006](https://user-images.githubusercontent.com/81608551/140007085-7f740ae3-f889-456e-a218-821583ad4eb5.png)
尝试更改密码但是还是无法登录

**Comment by jimlee2002** [comment]
目前看来密码似乎是一次性的，每个新密码在第一次成功登陆后将自动失效
因此更改密码后请勿马上在手机上重新登陆，应把新密码更新进 secrect，先跑一遍脚本
请再次重设密码试试看，如果还有问题建议等24小时后再更改密码重新尝试

**Comment by wxm78** [comment]
> 目前看来密码似乎是一次性的，每个新密码在第一次成功登陆后将自动失效
> 因此更改密码后请勿马上在手机上重新登陆，应把新密码更新进 secrect，先跑一遍脚本
> 请再次重设密码试试看，如果还有问题建议等24小时后再更改密码重新尝试

谢谢，解决了。
