### ISSUE TITLE
多账号

### ISSUE THREAD

**Issue by ninhua** [jimlee2002/WoZaiXiaoYuanPuncher-Actions#4]
怎么配置多账号打卡

**Comment by LeslieLeung** [comment]
可以通过以下方法实现（理论，未经测试）

1. 在`.github/workflows`下找到你需要多账号运行的脚本，复制一份，以其他名称命名（如`wzxy_healthcheck_2.yml`），然后保存到同一目录下；
2. 配置环境和对应参数，方法相同；但需要注意`USERNAME`、`PASSSWORD`等参数不能配置成`Repository secrets`（即教程的Step2中，不需要新增Repository secret，只需要新增在`Environment secrets`中；若你已添加Repository secret，请先删除，再在Environment secret中添加）；若多账号不需要分开进行消息推送，则通知类的secret可以填写在Repository secrets中，会发送到同一推送渠道；若需要分开推送，则请按照账号信息的方法进行操作。
3. 到Actions中启动该脚本即可。

**Comment by 1987980421** [comment]
我也想多账户，这样的话似乎不太方便

**Comment by LeslieLeung** [comment]
> 我也想多账户，这样的话似乎不太方便

如果使用“|”来分割多个账号这样方便吗？就是USERNAME里面可以填写多个账号，用“|”分隔，如“12345|54321”。

**Comment by 1987980421** [comment]
方便呀

**Comment by jimlee2002** [comment]
> 可以通过以下方法实现（理论，未经测试）
> 
> 1. 在`.github/workflows`下找到你需要多账号运行的脚本，复制一份，以其他名称命名（如`wzxy_healthcheck_2.yml`），然后保存到同一目录下；
> 2. 配置环境和对应参数，方法相同；但需要注意`USERNAME`、`PASSSWORD`等参数不能配置成`Repository secrets`（即教程的Step2中，不需要新增Repository secret，只需要新增在`Environment secrets`中；若你已添加Repository secret，请先删除，再在Environment secret中添加）；若多账号不需要分开进行消息推送，则通知类的secret可以填写在Repository secrets中，会发送到同一推送渠道；若需要分开推送，则请按照账号信息的方法进行操作。
> 3. 到Actions中启动该脚本即可。

是的，多账号可以利用 Github Actions 的功能实现，如 @LeslieLeung 所述，将某用户所有配置信息（包括原指南中使用 Repository Secret 的`USERNAME`、`PASSWORD`、`CACHE_NAME` 等 ）全部参照 Step2 第二张图用 Environment Secrect 储存。这样，一个用户就对应一个 Environment。
这样，需要添加新用户，只需要新建并设置好含有该用户数据的 Environment，并创建新的 workflow，在配置文件中修改 `environment:  ************` 字段为对应用户配置的 Envrionment 即可。
有空我再写个详细的配置指南吧。

**Comment by jimlee2002** [comment]
已支持多账户。
修改了默认的配置文件，请 Fetch 最新代码后参考新的文档重新配置所有 Secrect。
