### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by Minelu** [jimlee2002/WoZaiXiaoYuanPuncher-Actions#9]
提示登录错误，请检查账号信息，但是账号信息已经更新过了，求教

**Comment by jimlee2002** [comment]
这个问题我也偶尔遇到，即便密码正确也会block掉登录报101密码错误，猜测是由于频繁登陆导致的。
先暂时禁用所有脚本自动执行的工作流，重设下密码，等24h后再试试？记得把新密码写入secrect。

**Comment by Minelu** [comment]
> 换了好几个账号都是登陆失败，请检查账号信息 密码改了几次，大佬救命

在我的校园修改完密码后，执行脚本 🌚

**Comment by as1dfghjkl0** [comment]
> 
> 
> > 换了好几个账号都是登陆失败，请检查账号信息 密码改了几次，大佬救命
> 
> 在我的校园修改完密码后，执行脚本 🌚

找不到cache文件，正在使用账号信息登录...
{'code': 1, 'message': '请输入用户名和密码'}
登录失败，请检查账号信息
登陆失败，请检查账号信息
找不到文件怎么回事
密码改了

**Comment by as1dfghjkl0** [comment]
> 
> 
> > > > {'code': 1, 'message': '请输入用户名和密码'}
> > > > 登录失败，请检查账号信息
> > > > 这样报错了怎么弄呀，用户名和密码不用加引号吧
> > > 
> > > 
> > > 不用加引号。
> > > 看你action的执行日志，Secrect完全没识别到，请检查你的Environment和Secrect是否正确设置，名字是否正确。 如果搞不懂，建议删掉原来的新建一个，跟着文档走，全部重新配置一次。
> > 
> > 
> > 名字是填什么呢 我是按照文档弄的
> 
> 什么名字？

那个Environment和Secrect的名字是随便写吗还是？
value有没有格式的呀，我是小白不太懂

**Comment by as1dfghjkl0** [comment]
> 
> 
> > > > {'code': 1, 'message': '请输入用户名和密码'}
> > > > 登录失败，请检查账号信息
> > > > 这样报错了怎么弄呀，用户名和密码不用加引号吧
> > > 
> > > 
> > > 不用加引号。
> > > 看你action的执行日志，Secrect完全没识别到，请检查你的Environment和Secrect是否正确设置，名字是否正确。 如果搞不懂，建议删掉原来的新建一个，跟着文档走，全部重新配置一次。
> > 
> > 
> > 名字是填什么呢 我是按照文档弄的
> 
> 什么名字？

懂了懂了
原来Secret是一个一个打的
